# Generated by Django 5.2.5 on 2025-08-22 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_r', to=settings.AUTH_USER_MODEL)),
                ('user_s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_s', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
