# Generated by Django 5.2.5 on 2025-08-21 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='user_r',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='user_e',
            new_name='sender',
        ),
    ]
